/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3208210256',
          max: 0,
          min: 0,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_m4Fk',
          max: 0,
          min: 0,
          name: 'title',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_QHxk',
          max: 0,
          min: 0,
          name: 'description',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: '_clone_2iDq',
          maxSelect: 1,
          maxSize: 0,
          mimeTypes: [],
          name: 'image',
          presentable: false,
          protected: false,
          required: true,
          system: false,
          thumbs: ['200x0'],
          type: 'file',
        },
        {
          hidden: false,
          id: '_clone_YRHg',
          max: null,
          min: null,
          name: 'image_width',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: '_clone_vyZw',
          max: null,
          min: null,
          name: 'image_height',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: '_clone_iGP9',
          max: '',
          min: '',
          name: 'date',
          presentable: false,
          required: true,
          system: false,
          type: 'date',
        },
        {
          hidden: false,
          id: '_clone_oHPE',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: '_clone_X3cL',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'json958785764',
          maxSize: 1,
          name: 'likes_count',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
      ],
      id: 'pbc_2865244566',
      indexes: [],
      listRule: '',
      name: 'art_view',
      system: false,
      type: 'view',
      updateRule: null,
      viewQuery:
        'SELECT \n    art.id,\n    art.title,\n    art.description,\n    art.image,\n    art.image_width,\n    art.image_height,\n    art.date,\n    art.created,\n    art.updated,\n    (SELECT COUNT(*) FROM likes WHERE likes.art_id = art.id) AS likes_count\nFROM \n    art\nWHERE \n    art.published = TRUE',
      viewRule: null,
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_2865244566');

    return app.delete(collection);
  }
);
